### ISSUE TITLE
data-size uses width and height from original image and not from the linked processed image 

### ISSUE THREAD

**Issue by tpinne** [j0nnybrav079/photoswipe#1]
If you have for example an image in your gallery which is unprocessed 3000x2000px in size. Then the attribute of the link would render to `data-size="3000x2000"`.

But according to the demo and docs of Photoswipe that should reflect the actual size of the linked image. Which would be in a standard TYPO3 installation maxed out to 800px in width and 600px in height. According to the following default constants `styles.content.textmedia.linkWrap.width = 800m` and `styles.content.textmedia.linkWrap.height = 600m`.

Therefore you have a linked large image for the gallery of max 800x600px and it gets zoomed to fill all available space in the photoswipe UI. And that might end up showing unwanted artifacts depending on how large your browser window and monitors are.

**Comment by j0nnybrav079** [comment]
Hello @tpinne and thank you for your feedback. You are right, that is indeed an error. Do you have a pull request for me?
If not I will change it according to your issue in the next release

**Comment by tpinne** [comment]
Sorry, currently no time for a PR because it wasn't a showstopper for the customer. And now im already in the next project.

**Comment by j0nnybrav079** [comment]
unfortunately i do not know how to change file:current.size to get the size of the processed files. If somebody has an idea, or a solution, feel free to post it here :)

**Comment by j0nnybrav079** [comment]
fixed with version 2.0.1
