### ISSUE TITLE
data sizing only works if cropping in image editor is touched

### ISSUE THREAD

**Issue by m10a** [j0nnybrav079/photoswipe#10]
In v1.2.x the ATagParams were configured per Typoscript:

`lib.contentElement.settings.media.popup.linkParams{
    ATagParams.dataWrap = class="{$styles.content.textmedia.linkWrap.lightboxCssClass}" rel="{$styles.content.textmedia.linkWrap.lightboxRelAttribute}" data-size="{file:current:width}x{file:current:height}"
}`

Since v2 you do this in the service class ATagParams
Unfortunately now only witdh and height from the image manipulation editor are used and not the sizes of file:current as before.
So now the data sizes are only set if one has touched the image editor settings. If not, data sizes ar set to 0 with the effect that the image fills all available space.

Could you consider both settings resp. use file:current as fall back if cropping sizes are not set?

**Comment by j0nnybrav079** [comment]
oh, you are right, i will fix it and push a new version

**Comment by j0nnybrav079** [comment]
Hello @m10a 
I just tried to reproduce the error, but the aTagParams-Class works fine for me, means: even if i don't crop the image, I get the original width and heigt like this:
![screen](https://github.com/j0nnybrav079/photoswipe/assets/30262816/ed81afc8-bf08-4717-99b3-83e37beca880)

Furthermore, the service itself decides whether the image is cropped, or not. if not, it already uses the original dimensions. 

`
        $properties = 1 === $cropWidth && 1 === $cropHeight
            ? $fileCurrent->getProperties()
            : $this->getCroppedSize($this->cObj->getCurrentFile(), $fileCurrent->getReferenceProperties()['crop']);
`

Can you give me some more information how to reproduce your error?

**Comment by j0nnybrav079** [comment]
Hello @m10a 
I just tried to reproduce the error, but the aTagParams-Class works fine for me, means: even if i don't crop the image, I get the original width and heigt like this:

![screen](https://github.com/j0nnybrav079/photoswipe/assets/30262816/c69ed71a-6fe2-4793-97d8-768e532a3a94)

Furthermore, the service itself decides whether the image is cropped, or not. if not, it already uses the original dimensions. 

`
        $properties = 1 === $cropWidth && 1 === $cropHeight
            ? $fileCurrent->getProperties()
            : $this->getCroppedSize($this->cObj->getCurrentFile(), $fileCurrent->getReferenceProperties()['crop']);
`

Can you give me some more information how to reproduce your error?

**Comment by j0nnybrav079** [comment]
Hello @m10a 
I just tried to reproduce the error, but the aTagParams-Class works fine for me, means: even if i don't crop the image, I get the original width and heigt like this:

![screen](https://github.com/j0nnybrav079/photoswipe/assets/30262816/c8165f09-fce7-44ef-8d4f-003bc4c335ab)

Furthermore, the service itself decides whether the image is cropped, or not. if not, it already uses the original dimensions. 

`
        $properties = 1 === $cropWidth && 1 === $cropHeight
            ? $fileCurrent->getProperties()
            : $this->getCroppedSize($this->cObj->getCurrentFile(), $fileCurrent->getReferenceProperties()['crop']);
`

Can you give me some more information how to reproduce your error?

**Comment by j0nnybrav079** [comment]
Hello @m10a 
I just tried to reproduce the error, but the aTagParams-Class works fine for me, means: even if i don't crop the image, I get the original width and heigt like this:

![screen](https://github.com/j0nnybrav079/photoswipe/assets/30262816/db23c24e-2076-44d2-b4ec-188e554f7ee6)


Furthermore, the service itself decides whether the image is cropped, or not. if not, it already uses the original dimensions. 

![Unbenannt](https://github.com/j0nnybrav079/photoswipe/assets/30262816/b8f51f70-27c7-45ed-9b63-ea0cda56c1c9)

Can you give me some more information how to reproduce your error?

**Comment by m10a** [comment]
Hi @j0nnybrav079 ,

its a bit strange. In frontend I get this for the cropped image:

![touched](https://github.com/j0nnybrav079/photoswipe/assets/12715596/6e5dbd4f-680e-4074-a64b-6219e7e8c99a)

an this for the untouched one:

![untouched](https://github.com/j0nnybrav079/photoswipe/assets/12715596/e12bb895-d94f-4845-9791-676b87b7560f)

If I debug your `$properties` in `AtagParams->set()` I get for the cropped image:

![debug_touched](https://github.com/j0nnybrav079/photoswipe/assets/12715596/5c86bfbe-d7e3-4473-9c84-e7d13a14daca)

but in case of the untouched image the properties are empty:

![debug_untouched](https://github.com/j0nnybrav079/photoswipe/assets/12715596/67b477a7-9689-4d03-90b4-20cc36d8df6c)

But `$fileCurrent->getProperties()` delivers the full file object with all properties in both cases.

**Comment by m10a** [comment]
It's a TYPO3 12.4.14 just upgraded from 9.5, Text&Images CE ...

If I create a new CE and put the same images in, the error is gone. Perhaps something went wrong during the upgrade on database level. I have to look how many content elements are affected by this behaviour. Either I create them new or if too many I fall back on the old TS settings. 

Thanks, I think you can close this issue if your are not deeper interrested, it is of little importance and not worth the effort.

**Comment by m10a** [comment]
works!

**Comment by j0nnybrav079** [comment]
okay, then i will push this as new version 2.0.3

**Comment by m10a** [comment]
Great, thank you

**Comment by j0nnybrav079** [comment]
> Great, thank you

it is already as 2.0.4 on packagist.

**Comment by m10a** [comment]
could you raise the version number in ext_emconf too?

**Comment by j0nnybrav079** [comment]
done. 2.0.5 on packagist. 2.0.4 on TER includes the correct emconf.
