### ISSUE TITLE
Disable zoom in a lightbox?

### ISSUE THREAD

**Issue by opaque01** [j0nnybrav079/photoswipe#2]
Hallo,

how to implement disabling zoom in a lightbox (https://photoswipe.com/v5/docs/adjusting-zoom-level/)?

thx opaque

**Comment by j0nnybrav079** [comment]
Hello, this feature is not implemented, yet. If you want to, don't hesitate to create a pull request. I will work on this extension in a couple of days/weeks, then I will try to set it on the feature list.
