### ISSUE TITLE
Latest update to ImageSerivce64 uses PHP 7.4 language features

### ISSUE THREAD

**Issue by tpinne** [j0nnybrav079/photoswipe#3]
The latest changes to that service seem to use PHP 7.4 language features. But the composer.json only requires 7.2.

https://github.com/j0nnybrav079/photoswipe/blob/36360f37936bab416aa57cc271998842f8104eb5/Classes/Service/ImageService64.php#L16

I updated your extension to the latest version. On my local machine running 7.4 there were no errors. But on our Staging-Server currently behind at 7.3 I get the following error message. After upgrading the Staging-Servers PHP version to 7.4 it disappeared.

![Bildschirmfoto 2022-02-02 um 13 04 46](https://user-images.githubusercontent.com/1384345/152152137-d4b0f0d6-2725-4277-8480-1982f027741f.png)

So the composer.json should reflect those new PHP requirements or the type hint(s) must be removed and instead work with Doc comments @var notation to help the IDE. Then it should be fine too with lower PHP versions.

**Comment by j0nnybrav079** [comment]
Thank you for the hint and sorry for having trouble. I changed the composer-file as you recommended :)
