### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by GuidoJansenPI** [j0nnybrav079/photoswipe#4]
I just wanted to ask, if we could set the PHP version dependency to add 8.0 and 8.1 as well?

I ignored this restriction and got no problems

**Comment by j0nnybrav079** [comment]
Sure, I will push it within the next deployment!

**Comment by GuidoJansenPI** [comment]
Thanks

**Comment by viu-x** [comment]
As of now the latest tagged version is 1.2.4 which still uses PHP 7.4 as dependency. In the master branch this is changed. Any ETA for this as a tagged version?

**Comment by Hawkeye1909** [comment]
Same question as @viu-x. Could your please create a new tag?

**Comment by j0nnybrav079** [comment]
done.
