### ISSUE TITLE
ParseError with PHP 7.2.34

### ISSUE THREAD

**Issue by schi** [j0nnybrav079/photoswipe#5]
In TYPO3 CMS 10.4.31 with PHP 7.2.34 I get this:

(1/1) ParseError
syntax error, unexpected 'FrontendConfigurationManager' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
in /Users/heinzschilling/Web/werkhandkunst.test/typo3conf/ext/photoswipe/Classes/Service/ImageService64.php line 16

```
use TYPO3\CMS\Extbase\Service\ImageService;

class ImageService64
{
    protected FrontendConfigurationManager $frontendConfigurationManager;

    protected array $settings;

    public function injectFrontendConfigurationManager(FrontendConfigurationManager $fcm)
```

PHP 7.4.21 works.

**Comment by j0nnybrav079** [comment]
Hi! Do you need PHP 7.2? I would prefer to change composer to php 7.4 instead of polyfilling it?

**Comment by schi** [comment]
The you for your response. I have a TYPO3 CMS 10 which runs on PHP 7.2. See PHP Compatibility Chart on https://typo3.org/cms/roadmap. Maybe you want to mark newest version only works on TYPO3 CMS 11 which has a minimum requirement for PHP 7.4? If I want to use your extension I can fix it myself.
