### ISSUE TITLE
Links in figcaption not working.

### ISSUE THREAD

**Issue by simeonpfeiffer** [j0nnybrav079/photoswipe#7]
This is a common HTML structure:

```
<figure>
<img>
<figcaption>Text with a <a>link</a>.</figcaption>
</figure>
```

The link added by PhotoSwipe should only listen to click events on img, not on the whole figure including figcaption. The current behaviour is overriding any link in the figcaption.

**Comment by simeonpfeiffer** [comment]
Quick fix is adding this to photoswipe-init.js, line 62:

```
        if(e.target.tagName == "FIGCAPTION" || e.target.tagName == "A"){
            return;
        }
```

**Comment by j0nnybrav079** [comment]
added
